baskets_df_to_list:
    min_basket_size: 3
    shuffle: True
    to_string: True
    seed: 123
Word2Vec:
    vector_size: 15
    window: 2000
    min_count: 1
    alpha: 0.025
    min_alpha: 0.0001
    sample: 0.001
    sg: 1
    negative: 20
    epochs: 3
    compute_loss: False
    workers: 1
    seed: 1
TSNE:
    n_components: 2
    n_iter: 4000
    perplexity: 5
    init: "pca"
    angle: 0.5
    random_state: 123
    verbose: 0
MDS:
    n_components: 2
    max_iter: 4_000
    random_state: 123
    verbose: 0
    